### ISSUE TITLE
Update GUI

### ISSUE THREAD

**Issue by leawang0** [AY2324S1-CS2103T-W11-3/tp#86]
Must-have features that GUI needs to reflect includes:

- [X] Handle `list band` (also default behaviour) &rarr; display all musicians and bands
- [x] Handle `filter band` &rarr; display only filtered bands and musicians in those bands
- [x] Handle `find band` & `find musicians in band` &rarr; display correct band and musicians in that band
